### ISSUE TITLE
Add log framework adaptation

### ISSUE THREAD

**Issue by zc2638** [corazawaf/coraza#244]
## Summary

`waf.Logger` supports `logger` interface , `zap` is used by default, users can initialize their own logging framework.

### Motivation

<b>Why are we doing this? </b>

After `corazar` is used by other projects, the general project will unify the log output method.
Now `coraz` uses `zap` by default, but many users may not like to use this library to output logs. 
Of course, they also like to use the default debug log for debugging.

<b>What is the expected outcome?</b>
`zap` is used by default, but others can be used, such as `logrus`, `zerolog`, `standard library`, `lion`, etc.

**Comment by zc2638** [comment]
@jptosso

**Comment by zc2638** [comment]
Hi @jptosso ,

I looked at the v3 branch's log implementation code, but it's not what I expected.
From my point of view it's the same as no change, I still can't use my log.

**Comment by jptosso** [comment]
You can use `func (l *DebugLogger) SetOutput(w io.Writer)` to send your logs anywhere. There is no debug plugin architecture right now but if you have something in mind, feel free to push it. Your latest PR on logging is similar to the latest version, the only differences are the interfaces and Zap. I won't consider adding interfaces if we are not creating a plugin architecture for debug, unless we implement multiple debug loggers, which isn't the case right now.

Adding a debug logging plugin architecture is easy, the problem is that it's a niche feature and it requires tests, maintenance, and documentation.

**Comment by zc2638** [comment]
Well, maybe we define logs differently.
This only helps me with the output, but doesn't help me unify other things of the log like formatting.
We have full log monitoring and analysis, which can complicate an otherwise simple system.

This feature has been waiting too long, maybe I should consider customization, thanks.
