### ISSUE TITLE
[Web] Link to "Blog" section in Coraza.io web (which, in fact, points to https://www.tosso.io) doesn't respond

### ISSUE THREAD

**Issue by q2dg** [corazawaf/coraza#274]
It gives a poor impression to visitor.
Thanks!

**Comment by jptosso** [comment]
Hey, tosso.io is my personal blog, and it hosts all previous research for the coraza project since it was a personal project, and I only post about coraza. 

We don't have the resources right now to update our website and integrate a blog platform, but I will try to get the blog back online asap. In the near future, I would love to have a Coraza blog.
