### ISSUE TITLE
Only buffer body when inspecting it

### ISSUE THREAD

**Issue by jcchavezs** [corazawaf/coraza#497]
## Summary

Right now we are buffering the body no matter we inspect it or not. This is not only an overhead for stream like requests (as we buffer the entire payload instead of streaming it) but also a burden of reading/copying body even when not looking at it.

Relevant: https://github.com/corazawaf/coraza-proxy-wasm/pull/58#discussion_r1012920150

**Comment by M4tteoP** [comment]
I think it is more relevant to the connectors side rather than the Coraza side. Currently, the library is exporting the body buffers, it is up to the connectors to populate them in a smart way. Isn't it?

Related to it:
- Porting this issue [coraza-proxy-wasm side](https://github.com/corazawaf/coraza-proxy-wasm/issues/68).
- Opening https://github.com/corazawaf/coraza/pull/499 proposing to add RequestBodyAccessible and ResponseBodyAccessible. Making the connectors aware of these values could permit us to take more conscious decisions about buffering or not.

**Comment by jcchavezs** [comment]
Still missing the implementation of `IsRequestBodyProcessable`

**Comment by jcchavezs** [comment]
Makes sense @fzipi
