### ISSUE TITLE
IDEA: Add variable and key to operators

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#502]
Operators are not aware of which variable is being used. Variable awareness would allow the operator to make specific decisions based on the variable, for example handling body.

Other example is handling bodies from parameters, if we wanted to read a JSON from a POST URLENCODED parameter, we would have to send the parameter name as an operator argument. That way, the operator can assign a proper key to it.

New interface to replace `value string`
```go
type OperatorValue interface {
  Variable() types.RuleVariable
  Key() string
  Value() string
}
```

Maybe we could even replace Value with some generic value interface to cast the value into int, string, io.Reader, etc.

**Comment by jcchavezs** [comment]
I think that would make operators much more complicated and a pain for
users which need to know what is the behaviour for what variable. Too much
knowledge barrier.

I also looked at the existing operators and the only think I can think of
in terms of usefulness for operators to discriminate logic depending on
variable is mostly "when can I apply this operator" instead of make it
better decisions by knowing the name of the variable. Maybe coming up with
a concrete example would make things easier.

That said, I think it could make sense (if this is a concern actually to
fail fast when operator can't operate in a certain variable) is for the
operator to expose what variables it can operate on, e.g. if the operator
is `gt` or `lt` then let's don't run on non numeric (and show a nice
warning). Would that make sense? @M4tteoP @corazawaf/core-developers
<https://github.com/orgs/corazawaf/teams/core-developers>
