### ISSUE TITLE
Use case-insensitive matching for variable names resolved by the BodyProcessor

### ISSUE THREAD

**Issue by zpeasystart** [corazawaf/coraza#767]
## Description

**If the REQUEST BODY parameter name contains uppercase, it will not be matched by the rule variable name, because the rule variable name has been changed to lowercase at load time.**

### Steps to reproduce
```
HTTP:
POST / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Type: application/json
Content-Length: 11
Accept-Language: zh-CN,zh;q=0.9

{"Audio":6}
```
Rule:
`SecRule ARGS:json.Audio "@gt 5" "deny,status:-1,msg:'successful test',log,id:281647356379301,phase:2"`

### Result
The rule cannot be matched

### Expectation
![066e0a5909cf2c0892e76f8fd4965af](https://user-images.githubusercontent.com/44694500/231111913-5e079bb1-9175-4745-9af8-854e89e06a11.jpg)

**Comment by zpeasystart** [comment]
This may not be a bug, I'm just not sure what the purpose is

**Comment by jcchavezs** [comment]
Could you pease come up with a unit tests?

**Comment by M4tteoP** [comment]
Hi @zpeasystart, I'm not able to reproduce it against Coraza v3. The codebase had a lot of changes and improvements compared to v2. Specifically, the jsonBodyProcessor now [is calling `SetIndex`](https://github.com/corazawaf/coraza/blob/57b42eb8f524fe5bee1d3715a17c2fae23c407a5/internal/bodyprocessors/json.go#L27) which internally performs [strings.ToLower](https://github.com/corazawaf/coraza/blob/57b42eb8f524fe5bee1d3715a17c2fae23c407a5/internal/bodyprocessors/json.go#L27) (Just like you were expecting). Is there a specific reason you are running version 2? Otherwise, I would suggest to try out the `v3/dev` branch, or [v3.0.0-rc.1](https://github.com/corazawaf/coraza/releases/tag/v3.0.0-rc.1). Release candidate 2 is also pretty close :)
