### ISSUE TITLE
Create method SetResponseHeader

### ISSUE THREAD

**Issue by jcchavezs** [corazawaf/coraza#818]
## Summary

Currently it is only possible to add/append headers by using the method AddRequestHeader or  AddResponseHeader (see
https://github.com/corazawaf/coraza/blob/2fd87b892906bb5c35c80c87b4d4093001be09e6/internal/corazawaf/transaction.go#L335-L336) however, there are cases where you want to completely override such value, for example if a request gets denied base on the response at phase 4, we should be able to override the `content-length and potentially the `content-type`.

cc @jptosso @M4tteoP

**Comment by jptosso** [comment]
You can cast Transaction into TransactionState and manually override the collection map

**Comment by jcchavezs** [comment]
I guess so but is that desirable? Do we want to override a collection directly instead of use the right methods? cc @anuraaga

**Comment by M4tteoP** [comment]
More conceptually I'm thinking if it is something that we expect to do. We agreed that Coraza is not meant to manipulate the request/response. A setter would just change the value that is used internally to Coraza rather then propagating it downstream. I see that a deny Action at phase 4 is a corner case, but I conceptually see it more like a generation of a deny response that replaces the original one rather than a manipulation of Coraza elements that are describing the response that we are analyzing 🤔

**Comment by anuraaga** [comment]
Agree with @M4tteoP, I always thought the data in Coraza is original so wouldn't be based on how the connector implements a deny response

**Comment by jcchavezs** [comment]
Make sense.
