### ISSUE TITLE
Consider making key http/middleware functions public

### ISSUE THREAD

**Issue by MrWako** [corazawaf/coraza#982]
## Summary

Would it be possible to make the key middleware functions public. Specifically:
* [processRequest](https://github.com/corazawaf/coraza/blob/fc71a09e809b2d022bc44fe08806bcf8496b46bb/http/middleware.go#L27C6-L27C20)
* [obtainStatusCodeFromInterruptionOrDefault](https://github.com/corazawaf/coraza/blob/fc71a09e809b2d022bc44fe08806bcf8496b46bb/http/middleware.go#L179C6-L179C47)

### Basic example

With these public they could be included directly within a minimal request-only middleware implementation like this:

```
import (
	"net/http"

	"github.com/corazawaf/coraza/v3"
	coraza_http "github.com/corazawaf/coraza/v3/http"
)

type waf struct {
	waf coraza.WAF
}

// waf constructor here

func (w *waf) ServeHTTP(rw http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
        tx := w.waf.NewTransaction()
	defer func() {
		tx.ProcessLogging()
		if err := tx.Close(); err != nil {
			tx.DebugLogger().Error().Err(err).Msg("Failed to close the transaction")
		}
	}()

	if it, err := coraza_http.ProcessRequest(tx, r); err != nil {
		tx.DebugLogger().Error().Err(err).Msg("Failed to process request")
		return
	} else if it != nil {
		rw.WriteHeader(coraza_http.ObtainStatusCodeFromInterruptionOrDefault(it, http.StatusOK))
		return
	}

	next(rw, r)
}
```

### Motivation

There's quite a bit of great logic in the http/middleware that makes sense to be in the package where it can get wider usage/testing. However currently adopting the middleware also means adopting the [response-writer interceptor](https://github.com/corazawaf/coraza/blob/main/http/interceptor.go). The interceptor is non-trivial as it has to be able to delay returning status code until after the response body has been processed. Currently we're seeing complications with [response flushing](https://github.com/corazawaf/coraza/issues/967)

I only want to process requests at this point so being able to construct simpler middleware would be valuable.

**Comment by jcchavezs** [comment]
I am sorry I did not come back to you before @MrWako. We put a lot of effort in supporting most of the cases in the middleware and the idea is that it can be used in all cases. Drifting a function like ProcessRequest means we have to maintain half of the functionality with no clue or directives on what is the user doing with the second part (response processing). We'd rather address issues users might have so they can use the full middleware.

As for the response writer interceptor, it is indeed complicated but it is the way it is. Myself along with @anuraaga have been working in instrumentation for a while and unfortunately the http interface is complex and you need to address different kind of response writers (see for example https://github.com/openzipkin/zipkin-go/blob/master/middleware/http/server.go#L218) to not to break the server. More so, consider in here we have to hold the status code until we evaluated the response body if that is the case because upstream could say 200 but response body could be flagged as anomalous and hence we still need to return a 403 so we buffer everything until we are 100% sure on what the status code will be.

All said, we are more than happy to make integrations work :)

**Comment by MrWako** [comment]
thanks @jcchavezs - this was mostly motivated by issue https://github.com/corazawaf/coraza/issues/967 which turned out to be already fixed in master. Since we now have a fix this isn't so pressing, feel free to close this request. I agree the ideal is to be able to use the provided middleware and hopefully it will get plenty of testing/usage by the community. Thanks for your support.
